#!/usr/bin/env python3
"""ISO-NE: delivered and undelivered energy of its dispatchable wind and solar plants, monthly (session 149). INTERNAL.

Energy Research Warehouse (ERW) connector. One series table, warehouse/output/isone_ddg_undelivered_monthly.csv, from
ISO New England's ISO Express report "Aggregate Monthly DDG Undelivered Energy" (DDG: Do Not Exceed Dispatchable
Generator, ISO-NE's name for a wind or solar plant it dispatches by a limit):

    https://www.iso-ne.com/isoexpress/web/reports/operations/-/tree/aggregate-monthly-ddg-undelivered-energy   the page
    https://www.iso-ne.com/isoexpress/web/reports/download/docWidgetGetMore?start=0&treenode=aggregate-monthly-ddg-undelivered-energy
                                                                                                              its file list (JSON)
    https://www.iso-ne.com/static-assets/documents/<folder>/<file>.xlsx                                       a year's workbook

    python warehouse/connectors/isone_ddg_undelivered.py --pull [--limit N] [--reuse-list] [--raw-dir DIR]   # save ISO-NE's files (no data lock)
    python warehouse/connectors/isone_ddg_undelivered.py --write [--out-dir DIR] [--raw-dir DIR]             # build the table from them

THE RULING. The owner's of 7 October 2026: the file is pulled and held internal, about 1,000 rows. It is ISO-NE's own
monthly figure of what its wind and solar plants could have delivered and did not, the nearest thing ISO-NE publishes
to a curtailment series (session 144 found it and did not pull it). It is shown on no page: the curtailment page's
ISO-NE entry stays a placeholder.

THE WORKBOOK. One a year and fuel (wind from 2018, solar from 2025), named in ISO-NE's list "<YYYY> Undelivered Wind
(or Solar) Energy Aggregate Report". A sheet "Nomenclature" and seven sheets of twelve month lines, "<YYYY> System",
"<YYYY> ME", "<YYYY> System wo ME", "<YYYY> ORR_SO", "<YYYY> System wo ORR_SO", "<YYYY> Congested", "<YYYY>
Uncongested", each with the columns DE [MWH], UE [MWH], UE-NonBind [MWH], UE-Bind [MWH], percent UE, percent
UE-NonBind, percent UE-Bind. Every sheet is marked "ISO-NE Public". ISO-NE's own definitions (sheet Nomenclature):

    "Delivered Energy: the amount of energy generated by the plant."
    "Estimated Undelivered Energy is the sum of the UE-Non-Bind and UE-Bind (described below)"
    "UE-Non-Bind: undelivered energy during one or more time periods where a wind plant did not have a sensitivity to
     a binding transmission constraint, this is generally caused by the plant's energy supply offer indicating a
     preference to generate less MW than the theoretical maximum potentially achievable given the conditions at the
     plant."
    "UE-Bind: indicates that a wind plant likely had undelivered energy during one or more periods while the plant
     had a non-zero sensitivity to one or more binding transmission constraints"
    "Percentages in all charts and tables use UE+DE of the respective aggregation to normalize the respective values."

WHAT IS WRITTEN. The sheet "<YYYY> System" only: one row a fuel, month and figure, entity isone:system, freq P1M,
ts_utc the first of the month at 00:00:00Z. Variables <fuel>_delivered_mwh, <fuel>_undelivered_mwh,
<fuel>_undelivered_nonbinding_mwh, <fuel>_undelivered_binding_mwh (MWh, as printed) and <fuel>_undelivered_pct,
<fuel>_undelivered_nonbinding_pct, <fuel>_undelivered_binding_pct (ISO-NE's own fraction of UE + DE, times 100).
A blank cell (a month not yet published) is no row. A cell that is neither blank nor a number stops the read. Nothing
is summed, filled or estimated here. The six other sheets (Maine, the Orrington South interface, the congested and
uncongested groups) stay in the saved workbooks and are NOT in the table: with them the table would pass the ceiling.

THE CEILING, over every run of this connector (the manifest counts each request, and the rows are counted from the
workbooks kept, each as the table reads it): 2,000 rows of the series, 20 requests, 50 MB. The stop sits BEFORE the
request that would pass any of the three. The pull is made once; it is on no schedule, and a refresh needs a new
ruling.

HOW IT IS ASKED. A plain request, with the one contact string the ERW sends ("ERW research project,
github.com/SamuelEnrique/erw") and nothing else: no cookie, no account, no address of a person. The page's own
CAPTCHA guards its several-files download form, which is not used; each workbook is asked for at the address the
page's own list gives. An answer that is an access control (401, 403, or a page where a workbook should be) is
recorded and nothing more is asked. One try a request: a request that fails is recorded and left.

License: INTERNAL (the ERW's standing reading for ISO-NE, sessions 65, 85, 136, 138 and 140; the owner's ruling of
7 October 2026 for this file). ISO-NE's legal notice (https://www.iso-ne.com/legal-privacy, read 7 October 2026 and
saved by --pull as legal_notice.html, its hash and retrieval time in the manifest): "You are also hereby put on
notice that the Content is protected by copyright under United States laws. Any duplication of the Content or
non-personal use may violate copyright, trademark, and other laws." The table is not published: it is in no public
dataset, no download, no page.
"""

import argparse
import csv
import datetime as dt
import glob
import hashlib
import io
import json
import math
import os
import re
import sys
import time
import traceback

import pandas as pd
import requests

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import iso_prices as ip  # noqa: E402

CONNECTOR = "isone_ddg_undelivered"
NAME = "isone_ddg_undelivered_monthly"
SOURCE = "isone:ddg_undelivered_monthly"
ENTITY = "isone:system"
GEO = "US-CT,US-MA,US-ME,US-NH,US-RI,US-VT"
NODE = "aggregate-monthly-ddg-undelivered-energy"
HOST = "https://www.iso-ne.com"
PAGE = HOST + "/isoexpress/web/reports/operations/-/tree/" + NODE
LIST = HOST + "/isoexpress/web/reports/download/docWidgetGetMore?start={}&treenode=" + NODE
LEGAL = HOST + "/legal-privacy"
CONTACT = "ERW research project, github.com/SamuelEnrique/erw"
UA = {"User-Agent": CONTACT}
MAX_ROWS, MAX_REQUESTS, MAX_BYTES = 2_000, 20, 50 * 1024 * 1024
ROWS_EST = 84                 # the most one workbook can hold of the series: twelve months, seven figures
BYTES_EST = 2 * 1024 * 1024   # a workbook's size allowed for before it is asked (those read are under 200 kB)
LIST_STEP = 40
PAUSE = 3.0
RAW = os.path.join(ip.RAW_DIR, CONNECTOR)
FILE = re.compile(r"^/static-assets/documents/[A-Za-z0-9_/.-]+\.xlsx$")
DESCRIPTION = re.compile(r"^(\d{4}) Undelivered (Wind|Solar) Energy Aggregate Report$")
SHEET = "System"
MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
# the column's label with spaces and hyphens removed, lower case -> (the variable's ending, unit)
COLUMNS = {
    "de[mwh]": ("delivered_mwh", "MWh"),
    "ue[mwh]": ("undelivered_mwh", "MWh"),
    "uenonbind[mwh]": ("undelivered_nonbinding_mwh", "MWh"),
    "uebind[mwh]": ("undelivered_binding_mwh", "MWh"),
    "percentue": ("undelivered_pct", "pct"),
    "percentuenonbind": ("undelivered_nonbinding_pct", "pct"),
    "percentuebind": ("undelivered_binding_pct", "pct"),
}
TERMS = ("ISO-NE's legal notice: \"You are also hereby put on notice that the Content is protected by copyright under United States laws. "
         "Any duplication of the Content or non-personal use may violate copyright, trademark, and other laws.\" "
         "(https://www.iso-ne.com/legal-privacy, read 7 October 2026)")
MANIFEST_COLS = ["retrieved_at", "status", "bytes", "sha256", "kind", "file", "url", "published", "series_rows", "file_rows", "note"]


class CeilingStop(RuntimeError):
    """The next request would pass a ceiling: it is not made."""


class AccessStop(RuntimeError):
    """ISO-NE answered with an access control (401, 403, or a page where a workbook should be): not worked around."""


# ---------------------------------------------------------------- the saved files

def manifest_path():
    return os.path.join(RAW, "manifest.csv")


def manifest():
    if not os.path.exists(manifest_path()):
        return []
    with open(manifest_path(), encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def record(**row):
    os.makedirs(RAW, exist_ok=True)
    new = not os.path.exists(manifest_path())
    with open(manifest_path(), "a", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        if new:
            w.writerow(MANIFEST_COLS)
        w.writerow([row.get(c, "") for c in MANIFEST_COLS])


def workbooks():
    """The workbooks saved and still on disk, by address: {url: manifest row} (the newest copy of each)."""
    out = {}
    for r in manifest():
        if r["kind"] == "workbook" and r["status"] == "200" and os.path.exists(os.path.join(RAW, r["file"])):
            out[r["url"]] = r
    return out


def described():
    """{a workbook's address: ISO-NE's description of it} from every copy of the list saved."""
    out = {}
    for p in sorted(glob.glob(os.path.join(RAW, "lists", "*.json"))):
        with open(p, encoding="utf-8") as f:
            for d in json.load(f).get("data", []):
                out[HOST + str(d.get("path", ""))] = str(d.get("descriptionFormatted", "")).strip()
    return out


def read_kept():
    """[(address, manifest row, the rows the table keeps of it)] for every workbook kept, oldest year first."""
    names = described()
    out = []
    for url, r in workbooks().items():
        with open(os.path.join(RAW, r["file"]), "rb") as f:
            out.append((url, r, parse(f.read(), names.get(url, ""))))
    return sorted(out, key=lambda x: (x[2][0]["year"] if x[2] else 0, x[0]))


def counted():
    """(rows of the series in the workbooks kept, requests made, bytes received), over every run. The rows are counted
    from the files themselves, each as the table reads it, so the count cannot drift from the manifest."""
    m = manifest()
    return sum(len(rows) for _, _, rows in read_kept()), len(m), sum(int(r["bytes"] or 0) for r in m)


def room(what, rows_est=0, bytes_est=0):
    """Refuse, before it is made, the request that would pass a ceiling."""
    rows, reqs, nbytes = counted()
    if reqs + 1 > MAX_REQUESTS:
        raise CeilingStop(f"stopped before {what}: {reqs} requests made, the ceiling is {MAX_REQUESTS}")
    if nbytes + bytes_est > MAX_BYTES:
        raise CeilingStop(f"stopped before {what}: {nbytes:,} bytes received and {bytes_est:,} more would pass the ceiling of {MAX_BYTES:,}")
    if rows + rows_est > MAX_ROWS:
        raise CeilingStop(f"stopped before {what}: {rows:,} rows read and {rows_est:,} more would pass the ceiling of {MAX_ROWS:,}")
    return rows, reqs, nbytes


def now_utc():
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def http_get(url):
    return requests.get(url, headers=UA, timeout=120)


def fetch(url, kind, name, log, published="", description="", rows_est=0, bytes_est=0, note=""):
    """One request, counted before it is made and recorded whatever it answers; saved under RAW/<name>. One try: a
    request that fails is recorded with its error and left (20 requests leave no room for retries by habit)."""
    room(f"GET {url}", rows_est, bytes_est)
    try:
        r = http_get(url)
    except requests.RequestException as exc:
        record(retrieved_at=now_utc(), status="error", bytes=0, sha256="", kind=kind, file="", url=url, published=published,
               series_rows=0, file_rows=0, note=f"no answer: {type(exc).__name__}: {str(exc)[:160]}")
        raise RuntimeError(f"{url}: no answer ({type(exc).__name__})")
    body = r.content
    digest = hashlib.sha256(body).hexdigest()
    if r.status_code in (401, 403):
        record(retrieved_at=now_utc(), status=r.status_code, bytes=len(body), sha256=digest, kind="refused", file="", url=url,
               published=published, series_rows=0, file_rows=0, note="an access control: not worked around")
        raise AccessStop(f"HTTP {r.status_code} for {url}: an access control, nothing more asked")
    if r.status_code != 200:
        record(retrieved_at=now_utc(), status=r.status_code, bytes=len(body), sha256=digest, kind=kind, file="", url=url,
               published=published, series_rows=0, file_rows=0, note="not 200: recorded and left")
        raise RuntimeError(f"HTTP {r.status_code} for {url}")
    rel = re.sub(r"[^A-Za-z0-9._/-]+", "_", name)
    path = os.path.join(RAW, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(body)
    s_rows = f_rows = 0
    if kind == "workbook":
        if body[:2] != b"PK":
            record(retrieved_at=now_utc(), status=r.status_code, bytes=len(body), sha256=digest, kind="refused", file=rel, url=url,
                   published=published, series_rows=0, file_rows=0, note="not a workbook: a page where a file should be")
            raise AccessStop(f"{url}: a page where a workbook should be ({body[:60]!r}); nothing more asked")
        try:
            f_rows = file_lines(body)
            s_rows = len(parse(body, description))
        except Exception as exc:
            record(retrieved_at=now_utc(), status=r.status_code, bytes=len(body), sha256=digest, kind="unread", file=rel, url=url,
                   published=published, series_rows=0, file_rows=0, note=f"could not be read: {str(exc)[:200]}")
            raise
    record(retrieved_at=now_utc(), status=r.status_code, bytes=len(body), sha256=digest, kind=kind, file=rel, url=url,
           published=published, series_rows=s_rows, file_rows=f_rows, note=note)
    log(f"  GET {url}: {len(body):,} bytes" + (f", {s_rows:,} rows of the series" if kind == "workbook" else "") + f" ({rel})")
    time.sleep(PAUSE)
    return body


# ---------------------------------------------------------------- the list

def listed(text):
    """[(address, file name, the list's publish date as printed, ISO-NE's description)] for every workbook on one
    page of ISO-NE's list."""
    out = []
    for d in json.loads(text).get("data", []):
        path = str(d.get("path", ""))
        if FILE.match(path):
            out.append((HOST + path, os.path.basename(path), str(d.get("publishDate", "")).strip(), str(d.get("descriptionFormatted", "")).strip()))
    return out


# ---------------------------------------------------------------- the workbook

def file_lines(body):
    """The non-empty lines of every sheet of a workbook."""
    book = pd.read_excel(io.BytesIO(body), sheet_name=None, header=None)
    return int(sum(len(df.dropna(how="all")) for df in book.values()))


def label(cell):
    """A column's label as the parser knows it: lower case, with no space, hyphen or underscore."""
    return re.sub(r"[\s_-]+", "", str(cell).strip().lower())


def blank(cell):
    return cell is None or (isinstance(cell, float) and math.isnan(cell)) or (isinstance(cell, str) and not cell.strip())


def parse(body, description):
    """A year's workbook as the rows the table keeps: [dict(year, month, fuel, variable, value, unit)] from the sheet
    "<YYYY> System". description: ISO-NE's own, from its list ("2026 Undelivered Solar Energy Aggregate Report"): it
    names the year and the fuel, which the older file names do not. Anything that is not the layout read in session
    149 stops the read: a sheet, a column or a month line that is missing or new, text where a number should be."""
    m = DESCRIPTION.match(str(description).strip())
    if not m:
        raise RuntimeError(f"ISO-NE's description {description!r} is not '<YYYY> Undelivered Wind (or Solar) Energy Aggregate Report'")
    year, fuel = int(m.group(1)), m.group(2).lower()
    # every cell as the workbook holds it: pandas' habit of reading "N/A" or "NA" as an empty cell is turned off, so
    # that words where a number should be stop the read and are never taken for a month not yet published
    book = pd.read_excel(io.BytesIO(body), sheet_name=None, header=None, keep_default_na=False, na_values=[])
    names = {re.sub(r"\s+", " ", str(k).strip()).lower(): k for k in book}
    want = f"{year} {SHEET}".lower()
    if want not in names:
        raise RuntimeError(f"the workbook's sheets are {list(book)}: no sheet {year} {SHEET}")
    df = book[names[want]]
    head = next((i for i in range(len(df)) if any(label(c) == "de[mwh]" for c in df.iloc[i].tolist())), None)
    if head is None:
        raise RuntimeError(f"sheet {year} {SHEET}: no line with the column DE [MWH]")
    cols = {}
    for j, cell in enumerate(df.iloc[head].tolist()):
        if blank(cell):
            continue
        if label(cell) not in COLUMNS:
            raise RuntimeError(f"sheet {year} {SHEET}: a column {cell!r} that session 149 did not read")
        cols[j] = COLUMNS[label(cell)]
    if len(df) < head + 13:
        raise RuntimeError(f"sheet {year} {SHEET}: {len(df) - head - 1} lines under the columns, 12 months expected")
    out = []
    for k, month in enumerate(MONTHS):
        line = df.iloc[head + 1 + k].tolist()
        if str(line[0]).strip().lower()[:3] != month:
            raise RuntimeError(f"sheet {year} {SHEET}: line {k + 1} under the columns is {line[0]!r}, {month.capitalize()} expected")
        for j, (ending, unit) in cols.items():
            cell = line[j]
            if blank(cell):
                continue
            if isinstance(cell, bool) or not isinstance(cell, (int, float)):
                try:
                    cell = float(str(cell).strip().replace(",", ""))
                except ValueError:
                    raise RuntimeError(f"sheet {year} {SHEET}, {month.capitalize()}, {ending}: {line[j]!r} is not a number")
            value = float(cell)
            if not math.isfinite(value):
                raise RuntimeError(f"sheet {year} {SHEET}, {month.capitalize()}, {ending}: {line[j]!r} is not a finite number")
            if unit == "pct":
                value = round(value * 100, 10)  # ISO-NE prints a fraction of UE + DE
            out.append(dict(year=year, month=k + 1, fuel=fuel, variable=f"{fuel}_{ending}", value=value, unit=unit))
    return out


# ---------------------------------------------------------------- the pull

def pull(log, limit=10 ** 9, reuse_list=False):
    if ip.paused("isone"):
        log(ip.pause_line("isone"))
        return "paused: no request made"
    if not any(r["kind"] == "terms" and r["status"] == "200" for r in manifest()):
        fetch(LEGAL, "terms", "legal_notice.html", log, note="ISO-NE's legal notice, quoted in the table's header")
    saved = sorted(glob.glob(os.path.join(RAW, "lists", "*.json")))
    if reuse_list and saved:
        with open(saved[-1], encoding="utf-8") as f:
            text = f.read()
        log(f"  the list saved earlier is read again, no request ({os.path.basename(saved[-1])})")
    else:
        text = fetch(LIST.format(0), "list", f"lists/list_{dt.datetime.now(dt.timezone.utc):%Y%m%dT%H%M%SZ}.json", log).decode("utf-8", "replace")
    files = listed(text)
    n_all = len(json.loads(text).get("data", []))
    log(f"  ISO-NE's list: {n_all} entries, {len(files)} workbooks")
    if n_all >= LIST_STEP:
        log(f"  the list's first page is full ({n_all} entries): a second page is not asked for by this pull and is reported")
    got = 0
    for url, name, published, description in files:
        if url in workbooks():
            log(f"  kept already: {name} ({description})")
            continue
        if got >= limit:
            log(f"  --limit {limit}: {name} left for a later run")
            continue
        fetch(url, "workbook", "workbooks/" + name, log, published=published, description=description, rows_est=ROWS_EST, bytes_est=BYTES_EST,
              note=description)
        got += 1
    return f"{got} workbooks saved this run, {len(workbooks())} kept of {len(files)} listed"


# ---------------------------------------------------------------- the table

def build(log=lambda m: None):
    """The table's rows from the workbooks kept, and one line a workbook for the header. Two workbooks that print
    the same fuel and month stop the build: nothing is chosen between them."""
    rows, lines = [], []
    for url, r, recs in read_kept():
        for x in recs:
            rows.append(dict(entity=ENTITY, variable=x["variable"], ts_utc=f"{x['year']:04d}-{x['month']:02d}-01T00:00:00Z", value=x["value"], unit=x["unit"],
                             freq="P1M", geo=GEO, market="", node="", source=SOURCE, source_url=url, retrieved_at=r["retrieved_at"], vintage=""))
        months = sorted({x["month"] for x in recs})
        what = f"{recs[0]['year']} {recs[0]['fuel']}: {len(recs)} rows, months {months[0]} to {months[-1]}" if recs else "no month published"
        lines.append(f"{os.path.basename(r['file'])} ({what}; ISO-NE's list: published {r['published'] or 'not said'}; sha256 {r['sha256'][:16]})")
        log(f"  {lines[-1]}")
    s = pd.DataFrame(rows, columns=ip.SERIES_COLS)
    twice = s[s.duplicated(["entity", "variable", "ts_utc"], keep=False)]
    if len(twice):
        raise RuntimeError(f"{len(twice)} rows printed by two workbooks for one fuel, month and figure, for example {twice.iloc[0][['variable', 'ts_utc']].tolist()}")
    return s.sort_values(["variable", "ts_utc"]).reset_index(drop=True), lines


def checks(s):
    """ISO-NE's own figures against each other, reported and never corrected: the largest gap between UE and the sum
    of its two parts, and between ISO-NE's percent and UE over UE plus DE."""
    w = s.pivot(index="ts_utc", columns="variable", values="value")
    out = []
    for fuel in ("wind", "solar"):
        need = [f"{fuel}_delivered_mwh", f"{fuel}_undelivered_mwh", f"{fuel}_undelivered_nonbinding_mwh", f"{fuel}_undelivered_binding_mwh", f"{fuel}_undelivered_pct"]
        if not set(need) <= set(w.columns):
            continue
        g = w[need].dropna()
        if g.empty:
            continue
        parts = (g[need[1]] - g[need[2]] - g[need[3]]).abs()
        share = (g[need[4]] - 100 * g[need[1]] / (g[need[1]] + g[need[0]])).abs()
        out.append(f"{fuel}, {len(g)} months: UE differs from UE-NonBind plus UE-Bind by at most {parts.max():.6f} MWh ({parts.idxmax()[:7]}); "
                   f"ISO-NE's percent UE differs from UE over UE plus DE by at most {share.max():.8f} points ({share.idxmax()[:7]})")
    return out


def write(out_dir=None):
    if out_dir:
        ip.set_out_dir(out_dir)
    os.makedirs(ip.LOG_DIR, exist_ok=True)
    run_id = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    log = ip.Log(os.path.join(ip.LOG_DIR, f"{CONNECTOR}_{run_id}.log"))
    results = []
    try:
        rows, reqs, nbytes = counted()
        log(f"ERW {CONNECTOR} --write {run_id}: from the saved workbooks; {rows:,} rows of the series (ceiling {MAX_ROWS:,}), {reqs} requests (ceiling {MAX_REQUESTS}), "
            f"{nbytes:,} bytes (ceiling {MAX_BYTES:,})")
        s, lines = build(log)
        if s.empty:
            raise RuntimeError("no workbook is saved: run --pull first")
        found = checks(s)
        for c in found:
            log("  check: " + c)
        fuels = {f: (g["ts_utc"].min()[:7], g["ts_utc"].max()[:7], g["ts_utc"].nunique()) for f, g in s.groupby(s["variable"].str.split("_").str[0])}
        header = [
            "Energy Research Warehouse (ERW): ISO-NE, delivered and undelivered energy of its dispatchable wind and solar plants, monthly, the whole system (session 149). INTERNAL",
            "Shape: series (docs/datastandard.md v0). freq P1M: ts_utc is the first of the month at 00:00:00Z. Entity isone:system: the sheet \"<YYYY> System\" of ISO-NE's yearly workbook, "
            "its own aggregate of the wind (or solar) plants it dispatches by a limit (DDG, Do Not Exceed Dispatchable Generators).",
            "Variables, each as ISO-NE prints it: <fuel>_delivered_mwh = DE [MWH] (\"Delivered Energy: the amount of energy generated by the plant.\"); <fuel>_undelivered_mwh = UE [MWH] "
            "(\"Estimated Undelivered Energy is the sum of the UE-Non-Bind and UE-Bind\"); <fuel>_undelivered_nonbinding_mwh = UE-NonBind [MWH] (undelivered while the plant \"did not have a "
            "sensitivity to a binding transmission constraint\", \"generally caused by the plant's energy supply offer\"); <fuel>_undelivered_binding_mwh = UE-Bind [MWH] (undelivered while "
            "the plant \"had a non-zero sensitivity to one or more binding transmission constraints\").",
            "<fuel>_undelivered_pct, <fuel>_undelivered_nonbinding_pct, <fuel>_undelivered_binding_pct = ISO-NE's percent UE, percent UE-NonBind, percent UE-Bind: its own fraction of UE + DE "
            "(\"Percentages in all charts and tables use UE+DE of the respective aggregation to normalize the respective values.\"), written times 100.",
            "It is ISO-NE's ESTIMATE of undelivered energy, monthly, for the plants it dispatches: not a metered curtailment and not every wind or solar plant in New England.",
            "A blank cell (a month ISO-NE has not published) is no row. Nothing is summed, filled or estimated by the ERW. The workbook's six other sheets (ME, System wo ME, ORR_SO, "
            "System wo ORR_SO, Congested, Uncongested) are kept in the raw files and are not in this table.",
            "Held: " + "; ".join(f"{f} {a} to {b} ({n} months)" for f, (a, b, n) in sorted(fuels.items())) + ".",
            "Workbooks read: " + "; ".join(lines) + ".",
        ] + ["ISO-NE's figures against each other (reported, never corrected): " + c + "." for c in found] + [
            f"Retrieved: {run_id} (UTC) by warehouse/connectors/isone_ddg_undelivered.py --write, from the files --pull saved",
            f"Run log: warehouse/output/logs/{CONNECTOR}_{run_id}.log",
            f"Raw files: warehouse/raw/{CONNECTOR}/ (not in git; manifest.csv lists each request, its address, bytes and sha256; legal_notice.html is ISO-NE's notice as read)",
            f"Source: {SOURCE} ISO New England (ISO-NE), ISO Express, Aggregate Monthly DDG Undelivered Energy, {PAGE}",
            f"  access: {LIST.format(0)} and {HOST}/static-assets/documents/<folder>/<file>.xlsx; User-Agent \"{CONTACT}\", no cookie, no account",
            f"The pull against its ceilings, every run: {rows:,} rows of the series (ceiling {MAX_ROWS:,}); {reqs} requests (ceiling {MAX_REQUESTS}); {nbytes:,} bytes (ceiling {MAX_BYTES:,}).",
            f"License: internal. The owner's ruling of 7 October 2026: pulled and held internal. {TERMS}. Not published, in no public dataset, no download and no page.",
        ]
        ip.write_csv(s, NAME, header, log)
        detail = f"{len(s):,} rows this run, {s['ts_utc'].min()[:7]} to {s['ts_utc'].max()[:7]}; " + "; ".join(f"{f} {n} months" for f, (_, _, n) in sorted(fuels.items()))
        results.append(dict(table=NAME, market="all", status="ok", detail=detail))
        print(f"{NAME}: {detail}")
        for c in found:
            print("  check: " + c)
        if not out_dir:  # a trial leaves the registry alone
            ip.update_sources([dict(source=SOURCE, publisher="ISO New England (ISO-NE)",
                                    report="ISO Express, Aggregate Monthly DDG Undelivered Energy (yearly workbooks): delivered and estimated undelivered energy of the wind and solar "
                                           "plants ISO-NE dispatches, monthly, the whole system [terms: \"Any duplication of the Content or non-personal use may violate copyright, "
                                           "trademark, and other laws.\" (https://www.iso-ne.com/legal-privacy, read 7 October 2026); held internal by the owner's ruling of 7 October 2026]",
                                    report_url=PAGE, document_list=LIST.format(0), license="internal", tables=[NAME])])
    except Exception:
        tb = ip.redact(traceback.format_exc())
        log(f"{NAME} FAILED, no output file written:\n{tb}")
        print(f"{CONNECTOR} {NAME} FAILED, no output file written: {tb.strip().splitlines()[-1]}", file=sys.stderr)
        results.append(dict(table=NAME, market="all", status="failed", detail=tb.strip().splitlines()[-1][:300]))
    if not out_dir:
        ip.write_status(CONNECTOR, run_id, results)
    log.close()
    print(f"{CONNECTOR} run log: {log.path}")
    return 0 if all(r["status"] == "ok" for r in results) else 1


def main(argv=None):
    global RAW
    ap = argparse.ArgumentParser(description="ISO-NE's Aggregate Monthly DDG Undelivered Energy (internal)")
    ap.add_argument("--pull", action="store_true", help="save ISO-NE's files (no table is written, no data lock)")
    ap.add_argument("--write", action="store_true", help="build the table from the saved files (the data lock into warehouse/output)")
    ap.add_argument("--limit", type=int, default=10 ** 9, help="pull: at most N workbooks in this run")
    ap.add_argument("--reuse-list", action="store_true", help="pull: read the list saved by an earlier run, not ISO-NE's again (one request fewer)")
    ap.add_argument("--out-dir", help="write: the table under this folder, not warehouse/output (a trial; no data lock)")
    ap.add_argument("--raw-dir", help="another folder for the saved files (the main copy's raw store from a working copy, a trial or a test)")
    args = ap.parse_args(argv)
    if args.raw_dir:
        RAW = os.path.abspath(args.raw_dir)
    if not (args.pull or args.write):
        ap.error("one of --pull, --write")
    code = 0
    if args.pull:
        os.makedirs(RAW, exist_ok=True)
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        with open(os.path.join(RAW, f"pull_{stamp}.log"), "w", encoding="utf-8", newline="\n") as f:
            def say(msg):
                f.write(msg + "\n")
                f.flush()
                print(msg)
            try:
                say(f"ERW {CONNECTOR} --pull {stamp}; ceilings {MAX_ROWS:,} rows, {MAX_REQUESTS} requests, {MAX_BYTES:,} bytes")
                out = pull(say, args.limit, args.reuse_list)
            except (CeilingStop, AccessStop) as exc:
                out = f"stopped: {exc}"
                code = 1
            except Exception:
                out = "failed: " + traceback.format_exc().strip().splitlines()[-1]
                say(traceback.format_exc())
                code = 1
            rows, reqs, nbytes = counted()
            say(f"pull: {out}. In all: {rows:,} rows of the series in the workbooks kept (ceiling {MAX_ROWS:,}); {reqs} requests (ceiling {MAX_REQUESTS}); "
                f"{nbytes:,} bytes (ceiling {MAX_BYTES:,})")
    if args.write and code == 0:
        code = write(args.out_dir)
    return code


if __name__ == "__main__":
    sys.exit(main())
