#!/usr/bin/env python3
"""Write docs/OVERVIEW.md: the Energy Research Warehouse (ERW) on one page, for reviewers.

Energy Research Warehouse (ERW), session 20. Every number on the page is read from a file here,
none typed by hand:
  counts            warehouse/metadata/coverage.csv (tables, rows, licenses, derived) and
                    warehouse/metadata/sources.csv (sources, licenses, news outlets)
  the site          site/lib/pages.ts (every page, its group and one-line description); the URL README.md links
  tools             docs/platform-tools.md (status yes or partial, and the site pages each row names)
  refresh           the cron lines of .github/workflows/*.yml
  evaluation        warehouse/chat/eval/results/*.md (chat), warehouse/news/eval/eval_sample.csv
                    (news scoring behind the digest), warehouse/deals/eval/spot_check_s15.csv and
                    warehouse/datacenters/eval/spot_check_s16.csv; a chat run's session is the
                    SESSION_*_REPORT.md that names its run id
  open gaps         STATUS.md (its failed tables and open gap days)

    python warehouse/metadata/build_overview.py
"""

import glob
import os
import re

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "docs", "OVERVIEW.md")


def rd(*p):
    return open(os.path.join(ROOT, *p), encoding="utf-8").read()


def n(x):
    return f"{int(x):,}"


def site_url():
    """The deployed site, as README.md links it."""
    m = re.search(r"\*\*The site: \[([^\]]+)\]\((https://[^)]+)\)\*\*", rd("README.md"))
    return m.group(2) if m else ""


def pages():
    """[(group, href, label, line)] from site/lib/pages.ts."""
    src = rd("site", "lib", "pages.ts")
    out = []
    for g in re.finditer(r'label: "([^"]+)",\s*pages: \[(.*?)\],\n  \}', src, re.S):
        for p in re.finditer(r'href: "([^"]+)", label: "([^"]+)", line: "([^"]+)"', g.group(2)):
            out.append((g.group(1), *p.groups()))
    return out


def tools(hrefs):
    """[(number, name, status, [pages])] for the tools whose data layer is yes or partial."""
    out = []
    for ln in rd("docs", "platform-tools.md").splitlines():
        m = re.match(r"^\| (\d+) \| ([^|]+) \| [^|]* \| \*\*(yes|partial)\b", ln)
        if m:
            found = [h for h in sorted(hrefs, key=len, reverse=True) if f"`{h}`" in ln or f"`{h}/" in ln]
            out.append((int(m.group(1)), m.group(2).strip(), m.group(3), sorted(set(found))))
    return out


CRON_WORDS = {"0 14 * * *": "every day at 14:00 UTC", "*/15 * * * *": "every 15 minutes",
              "0 13 * * 1": "Mondays at 13:00 UTC"}


def schedules():
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, ".github", "workflows", "*.yml"))):
        s = open(f, encoding="utf-8").read()
        name = re.search(r"^name: (.+)$", s, re.M).group(1).strip()
        for c in re.findall(r'cron: "([^"]+)"', s):
            out.append((name, os.path.relpath(f, ROOT).replace("\\", "/"), c, CRON_WORDS.get(c, f"cron {c}")))
    return out


def chat_runs():
    reports = {f: open(f, encoding="utf-8").read() for f in glob.glob(os.path.join(ROOT, "SESSION_*_REPORT.md"))}
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "warehouse", "chat", "eval", "results", "*.md"))):
        run = os.path.basename(f)[:-3]
        s = open(f, encoding="utf-8").read()
        m = re.search(r"\| Correct \| (\d+) of (\d+)", s)
        cost = re.search(r"\| Total cost \| USD ([0-9.]+)", s)
        sess = sorted(int(re.search(r"SESSION_(\d+)_REPORT", k).group(1)) for k, v in reports.items() if run in v)
        if m:
            out.append((run, int(m.group(1)), int(m.group(2)), cost.group(1) if cost else "", sess[0] if sess else None))
    return out


def main():
    cov = pd.read_csv(os.path.join(ROOT, "warehouse", "metadata", "coverage.csv"), dtype=str, keep_default_na=False)
    cov["n_rows"] = cov["n_rows"].astype(int)
    src = pd.read_csv(os.path.join(ROOT, "warehouse", "metadata", "sources.csv"), dtype=str, keep_default_na=False)
    news = src["report"].str.startswith("news stories")
    pub = cov[cov["license"] == "public"]
    P = pages()
    hrefs = {h for _, h, _, _ in P}
    T = tools(hrefs)
    L = [
        "# The Energy Research Warehouse (ERW) on one page",
        "",
        "Generated by `warehouse/metadata/build_overview.py` from the files it names; no number on this page is typed by hand. "
        "Rebuild it with `python warehouse/metadata/build_overview.py`.",
        "",
        "## What it is",
        "",
        "The live, citable record of the US energy system: prices, flows, projects, deals and policy across power, natural gas, oil, "
        "nuclear, renewables, storage and transmission. One connector per source reshapes each source into one of three table "
        "shapes (series, entities, events); a validator gates every table; every row names its source report and retrieval time. "
        "Redivis is the store of record (a human releases each version), Supabase holds a live subset for the public site, and "
        "GitHub Actions runs everything on a schedule. See `CLAUDE.md`, `ARCHITECTURE.md` and `docs/datastandard.md`.",
        "",
        "## Counts",
        "",
        "From `warehouse/metadata/coverage.csv` and `warehouse/metadata/sources.csv`:",
        "",
        "| | Tables | Rows |",
        "|---|---|---|",
        f"| All tables | {n(len(cov))} | {n(cov['n_rows'].sum())} |",
        f"| Public (on the site and in the package) | {n(len(pub))} | {n(pub['n_rows'].sum())} |",
        f"| Internal (licensed for internal use only) | {n((cov['license'] == 'internal').sum())} | "
        f"{n(cov.loc[cov['license'] == 'internal', 'n_rows'].sum())} |",
        f"| Derived by the ERW from other ERW tables | {n((cov['derived'] == 'yes').sum())} | "
        f"{n(cov.loc[cov['derived'] == 'yes', 'n_rows'].sum())} |",
        f"| Passing the validator | {n(cov['validator_status'].str.startswith('pass').sum())} of {n(len(cov))} | |",
        "",
        f"Sources in the registry: {n(len(src))}: {n((~news).sum())} data sources ({n((src.loc[~news, 'license'] == 'public').sum())} "
        f"public, {n((src.loc[~news, 'license'] == 'internal').sum())} internal) and {n(news.sum())} news outlets (internal: titles "
        "and summaries are not republished).",
        "",
        "## The site",
        "",
        (f"{site_url()}: " if site_url() else "") + "Next.js on Vercel, reading Supabase with the anonymous key only. "
        "Every page, from `site/lib/pages.ts`:",
        "",
        "| Group | Page | What it shows |",
        "|---|---|---|",
    ]
    L += [f"| {g} | `{h}` | {line} |" for g, h, _, line in P]
    L += ["", "## Tools that are live", "",
          f"From `docs/platform-tools.md`: {len(T)} of the platform's tools have a data layer that exists "
          f"({sum(1 for t in T if t[2] == 'yes')} yes, {sum(1 for t in T if t[2] == 'partial')} partial).", "",
          "| # | Tool | Data layer | Pages |", "|---|---|---|---|"]
    L += [f"| {num} | {name} | {status} | {', '.join(f'`{p}`' for p in ps)} |" for num, name, status, ps in T]
    L += ["", "## What refreshes when", "", "From the cron lines of `.github/workflows/`:", "",
          "| Workflow | File | Schedule |", "|---|---|---|"]
    L += [f"| {name} | `{f}` | {words} (`{c}`) |" for name, f, c, words in schedules()]
    L += ["", "The daily run (`warehouse/run_daily.sh`) pulls every source, runs the derived tables, the news "
          "(ingest, scoring, deals, datacenters, the digest and its email), validates, rebuilds coverage, loads the Supabase "
          "live set and uploads changed tables to the Redivis draft; the ISO interconnection queues are pulled on Mondays."]
    runs = chat_runs()
    L += ["", "## Evaluation to date", "", "**Chat** (`warehouse/chat/`, answers scored against pandas; "
          "`warehouse/chat/eval/results/`):", "", "| Run | Session | Correct | Cost (USD) |", "|---|---|---|---|"]
    L += [f"| `{r}` | {s if s else ''} | {c} of {t} ({100 * c / t:.0f}%) | {cost} |" for r, c, t, cost, s in runs]
    nd = pd.read_csv(os.path.join(ROOT, "warehouse", "news", "eval", "eval_sample.csv"), dtype=str, keep_default_na=False)
    marked = int((nd["human_significance"] != "").sum())
    ds = pd.read_csv(os.path.join(ROOT, "warehouse", "deals", "eval", "spot_check_s15.csv"), dtype=str, keep_default_na=False)
    v = ds[[c for c in ds.columns if c.endswith("_ok")]].stack()
    v = v[v != ""]
    dc = pd.read_csv(os.path.join(ROOT, "warehouse", "datacenters", "eval", "spot_check_s16.csv"), dtype=str, keep_default_na=False)
    dj = dc[dc["ok"] != ""]
    L += ["",
          f"**News scoring behind the digest** (`warehouse/news/eval/eval_sample.csv`): {len(nd)} stories sampled; "
          f"{marked} scored by a human so far, so the model's scores are not yet benchmarked"
          + ("." if marked == 0 else f" ({marked} rows)."),
          f"**Deals** (`warehouse/deals/eval/spot_check_s15.csv`): {n(len(ds))} deals, {n((v == '1').sum())} of {n(len(v))} field "
          f"values correct ({(v == '1').mean():.2f}).",
          f"**Datacenters** (`warehouse/datacenters/eval/spot_check_s16.csv`): {n((dj['ok'] == '1').sum())} of {n(len(dj))} "
          f"judgments correct ({(dj['ok'] == '1').mean():.2f})."]
    st = rd("STATUS.md")
    gap = re.search(r"Recorded gap days: (\d+); filled since: (\d+); open: (\d+)\.", st)
    failed = re.search(r"## Tables whose last run failed\n\n(.*?)\n\n", st, re.S)
    L += ["", "## Open gaps", "", "From `STATUS.md` (generated with coverage):", ""]
    if failed:
        rows = [ln for ln in failed.group(1).splitlines() if ln.startswith("| `")]
        L.append(f"**Tables whose last run failed: {len(rows)}.**")
        L += [""] + [ln for ln in failed.group(1).splitlines()]
    if gap:
        L += ["", f"**Days a per-day connector could not write complete:** {gap.group(1)} recorded, {gap.group(2)} filled "
              f"since, {gap.group(3)} open (per table and day in `STATUS.md`)."]
    L += ["", "Named gaps in the tools themselves (PJM prices, an ERCOT large-load list, SPP real time, MISO curtailment, "
          "and others) are in the Data layer column of `docs/platform-tools.md`.", ""]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(cov)} tables, {len(P)} pages, {len(T)} live tools, {len(runs)} chat runs")


if __name__ == "__main__":
    main()
