#!/usr/bin/env python3
"""Write STATUS.md: what the Energy Research Warehouse (ERW) holds and how its runs are going.

Energy Research Warehouse (ERW), session 14. Regenerated by the daily run
(warehouse/run_daily.sh, after coverage) and committed by the daily workflow.

    python warehouse/metadata/build_status.py

Every number is read, never typed:
- tables and rows: warehouse/metadata/coverage.csv (generated on every run);
- the daily run: warehouse/metadata/run_status.csv, the newest run on the GitHub
  runner and the newest local run, with their per-table outcomes;
- the 15-minute latest-prices job: the newest retrieved_at in Supabase's
  latest_prices table (SUPABASE_URL with SUPABASE_SERVICE_KEY or SUPABASE_ANON_KEY),
  since that job writes no run record of its own;
- open gaps: every day a per-day connector recorded as a "gap" in run_status.csv,
  re-checked against the table itself with the same completeness rule the connector
  uses (iso_prices.missing_report for ISO tables, the core-variable rule for
  EIA-930). A gap is listed until the table holds that day completely; a table not
  on this machine is listed as not verifiable here, never assumed filled.
"""

import datetime as dt
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "warehouse", "connectors"))
import iso_prices as ip  # noqa: E402
import eia930  # noqa: E402

COVERAGE = os.path.join(HERE, "coverage.csv")
RUN_STATUS = os.path.join(HERE, "run_status.csv")
OUT = os.path.join(ROOT, "STATUS.md")
STEP = {"PT1H": "1h", "PT15M": "15min"}


def env(name):
    v = os.environ.get(name)
    if not v:
        try:
            from dotenv import dotenv_values
            v = dotenv_values(os.path.join(ROOT, ".env")).get(name)
        except ImportError:
            v = None
    return (v or "").strip()


def latest_prices_last_run():
    """(newest retrieved_at, rows) in Supabase latest_prices, or (None, reason)."""
    url, key = env("SUPABASE_URL"), env("SUPABASE_SERVICE_KEY") or env("SUPABASE_ANON_KEY")
    if not url or not key:
        return None, "no Supabase credentials on this machine"
    try:
        import requests
        from urllib.parse import urlparse
        u = urlparse(url)
        r = requests.get(f"{u.scheme}://{u.netloc}/rest/v1/latest_prices",
                         params={"select": "retrieved_at,ts_utc", "order": "retrieved_at.desc"},
                         headers={"apikey": key, "Authorization": f"Bearer {key}"}, timeout=60)
        r.raise_for_status()
        rows = r.json()
    except Exception as exc:
        return None, f"Supabase not readable ({type(exc).__name__})"
    if not rows:
        return None, "latest_prices is empty"
    return rows[0]["retrieved_at"], len(rows)


# Session 34: the partitioned EIA-930 tables (column ba) and the variables whose 24 hours make a day complete; a gap
# row names the partition first ("swpp 2026-09-28") and, for one of the emissions table's six others, the variable
CORE_OF = {"eia930_all_emissions": {"co2_emissions_generated", "co2_emissions_consumed"},
           "eia930_all_storage": {"net_generation_battery_mw"}}
_COUNTS = {}


def partition_counts(table, path):
    """Session 34: {(ba, variable, UTC day): hours with a value} of a partitioned table, from one streamed pass,
    kept for every gap of the table (the emissions table has 4 million rows; it is read once, never whole)."""
    if table not in _COUNTS:
        import pyarrow as pa
        import pyarrow.csv as pcsv
        with open(path, encoding="utf-8") as f:
            skip = sum(1 for ln in f if ln.startswith("#"))
        cols = ["ba", "variable", "ts_utc", "value"]
        reader = pcsv.open_csv(path, read_options=pcsv.ReadOptions(skip_rows=skip, block_size=1 << 24),
                               convert_options=pcsv.ConvertOptions(include_columns=cols,
                                                                   column_types={c: pa.string() for c in cols}))
        counts = {}
        for b in reader:
            d = b.to_pandas()
            d = d[d["value"] != ""]
            g = d.groupby([d["ba"], d["variable"], d["ts_utc"].str[:10]]).size()
            for k, n in g.items():
                counts[k] = counts.get(k, 0) + int(n)
        _COUNTS[table] = counts
    return _COUNTS[table]


def is_day(text):
    """Session 149: whether a gap's day is a calendar day (YYYY-MM-DD). The interchange connector records one gap row
    for all its incomplete pair-days, with the market "pairs": it names no day, so there is no day to re-check."""
    try:
        return len(str(text)) == 10 and dt.date.fromisoformat(str(text)) is not None
    except ValueError:
        return False


def day_complete(table, day, part=None, variable=None):
    """True or False from the table on disk, None if the table is not on this machine (or, session 149, if the gap
    names no day, or the table is of another shape than the per-day re-check reads)."""
    if not is_day(day):
        return None
    path = os.path.join(ip.OUT_DIR, table + ".csv")
    if not os.path.exists(path):  # session 29: a member of a consolidated table, where consolidate.py build moved it
        path = os.path.join(ip.OUT_DIR, "members", table + ".csv")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        cols = next(ln for ln in f if not ln.startswith("#")).strip().split(",")
    if part is not None and "ba" in cols:  # session 34: a partitioned table: its core variables, or the gap's own
        counts = partition_counts(table, path)
        want = {variable} if variable else CORE_OF.get(table, eia930.CORE)
        present = {v for (b, v, d) in counts if b == part} & want
        return bool(present) and all(counts.get((part, v, day), 0) == 24 for v in present) and present == want
    if cols != ip.SERIES_COLS:
        # Session 149: a table with columns of its own (eia930_all_interchange: ba, x_to_ba) and a gap that names no
        # partition. read_series refuses a file of another shape, and that refusal failed the STATUS.md step on every
        # daily run from 2 October 2026. Such a gap is listed, not re-checked.
        return None
    df = ip.read_series(path)
    ts = pd.to_datetime(df["ts_utc"], utc=True)
    if table.startswith("eia930_"):  # EIA-930: UTC days, the core variables complete
        d0 = pd.Timestamp(day, tz="UTC")
        d1 = d0 + pd.Timedelta(days=1)
        part = pd.DataFrame({"variable": df["variable"], "interval_start": ts, "value": df["value"]})
        part = part[(part["interval_start"] >= d0) & (part["interval_start"] < d1)]
        problems, _ = eia930.incomplete_variables(part, d0, d1)
        core = set(df["variable"]) & eia930.CORE
        return not any(v in core for v in problems) and core <= set(part["variable"])
    iso = table.split("_")[0]  # ISO tables: the ISO's local operating day, every node and interval
    if iso not in ip.ISOS:
        # session 58: a table of several ISOs (iso_hub_prices_history, the consolidated iso_* tables) has no one operating day
        # here; its gap is listed, not re-checked. On 2026-10-02 the daily run's STATUS.md step failed here (KeyError 'iso').
        return None
    tz = ip.ISOS[iso][2]
    d0 = pd.Timestamp(day).tz_localize(tz)
    d1 = pd.Timestamp(pd.Timestamp(day).date() + dt.timedelta(days=1)).tz_localize(tz)
    step = STEP[df["freq"].iloc[0]]
    rows = pd.DataFrame({"node": df["node"], "interval_start": ts})
    rows = rows[(rows["interval_start"] >= d0) & (rows["interval_start"] < d1)]
    _, problems = ip.missing_report(rows, sorted(df["node"].unique()), d0, d1, step)
    return not problems


KNOWN_GAPS = os.path.join(ROOT, "warehouse", "metadata", "known_gaps.csv")


def health_gate(rs):
    """Session 28 (PRIORITIES.md, the health gate): the latest daily run on GitHub and its failed tables
    that are not in warehouse/metadata/known_gaps.csv. Returns (run day, failures outside the list, known)."""
    known = pd.read_csv(KNOWN_GAPS, dtype=str, keep_default_na=False) if os.path.exists(KNOWN_GAPS)         else pd.DataFrame(columns=["table", "reason", "since", "decided"])
    gh = rs[rs["runner"] == "github"]
    if gh.empty:
        return None, None, known
    last = gh["run_id"].max()
    day = gh[gh["run_id"].str[:8] == last[:8]]
    newest = day.sort_values("run_id").groupby(["connector", "table"]).tail(1)
    failed = newest[newest["status"] == "failed"]
    outside = failed[~failed["table"].isin(set(known["table"]))]
    return last[:8], outside, known


def main():
    if "--gate" in sys.argv:  # session 28: exit 1 while the health gate is closed
        rs = pd.read_csv(RUN_STATUS, dtype=str, keep_default_na=False)
        day, outside, _ = health_gate(rs)
        if day is None:
            print("health gate: no daily run on GitHub recorded")
            return 1
        print(f"health gate {'OPEN' if outside.empty else 'CLOSED'}: daily run on GitHub {day}, "
              f"{len(outside)} failed tables outside warehouse/metadata/known_gaps.csv"
              + ("" if outside.empty else ": " + ", ".join(sorted(outside["table"]))))
        return 0 if outside.empty else 1
    now = pd.Timestamp.now(tz="UTC")
    cov = pd.read_csv(COVERAGE, dtype=str, keep_default_na=False)
    cov["n_rows"] = cov["n_rows"].astype(int)
    rs = pd.read_csv(RUN_STATUS, dtype=str, keep_default_na=False)

    L = ["# ERW status", "",
         f"Generated {now:%Y-%m-%d %H:%M} UTC by `warehouse/metadata/build_status.py`, which the daily run "
         "regenerates after coverage; the daily workflow commits it. Every number below is read from "
         "`warehouse/metadata/coverage.csv`, `warehouse/metadata/run_status.csv` or Supabase.", ""]

    pub = cov[cov["license"] == "public"]
    L += ["## Tables", "",
          "| | Tables | Rows |", "|---|---|---|",
          f"| All | {len(cov)} | {cov['n_rows'].sum():,} |",
          f"| Public | {len(pub)} | {pub['n_rows'].sum():,} |",
          f"| Internal (never shown publicly) | {len(cov) - len(pub)} | {cov['n_rows'].sum() - pub['n_rows'].sum():,} |",
          "", f"Newest table refresh: {cov['last_run'].max().replace('T', ' ').rstrip('Z')} UTC. "
          f"Validator: {int((cov['validator_status'] == 'pass').sum())} of {len(cov)} tables pass. "
          "Per-table detail: [`docs/coverage.md`](docs/coverage.md).", ""]

    # session 28: the health gate (PRIORITIES.md) and the known-gap list it reads
    gday, outside, known = health_gate(rs)
    L += ["## Health gate", ""]
    if gday is None:
        L += ["No daily run on GitHub recorded yet, so the gate cannot be read.", ""]
    else:
        L += [f"**{'Open' if outside.empty else 'Closed'}.** The latest daily run on GitHub ({gday[:4]}-{gday[4:6]}-{gday[6:]}) "
              f"has {len(outside)} failed table{'' if len(outside) == 1 else 's'} outside the known-gap list below"
              + ("." if outside.empty else ": " + ", ".join(f"`{t}`" for t in sorted(outside["table"])) + ".")
              + " While the gate is closed, no session adds a new source or a new tool (`PRIORITIES.md`); fixing the "
              "failures, or a human adding one to the list, opens it. `python warehouse/metadata/build_status.py --gate` "
              "exits 1 while it is closed.", ""]
    L += ["### Known gaps", "", "Failures a human has accepted for now (`warehouse/metadata/known_gaps.csv`, edited by hand). "
          "A table here does not close the gate.", ""]
    if known.empty:
        L += ["None.", ""]
    else:
        L += ["| Table | Why | Since | Decided |", "|---|---|---|---|"]
        for r in known.itertuples():
            L.append(f"| `{r.table}` | {r.reason.replace('|', '/')} | {r.since} | {r.decided.replace('|', '/')} |")
        L.append("")

    L += ["## Last runs", "", "| Workflow | Last run (UTC) | Outcome |", "|---|---|---|"]
    for runner, label in (("github", "daily prices, on GitHub"), ("local", "daily run, local")):
        r = rs[rs["runner"] == runner]
        if r.empty:
            L.append(f"| {label} | none recorded | |")
            continue
        last = r["run_id"].max()
        day = r[r["run_id"].str[:8] == last[:8]]  # every connector's run of that day
        counts = day["status"].value_counts().to_dict()
        when = pd.Timestamp(last.replace("Z", ""), tz="UTC")
        outcome = ", ".join(f"{counts[k]} {k}" for k in ("ok", "failed", "gap", "skipped") if k in counts)
        L.append(f"| {label} | {when:%Y-%m-%d %H:%M} | {outcome} (table results of that day) |")
    last_lp, info = latest_prices_last_run()
    if last_lp:
        L.append(f"| latest prices, every 15 minutes | {last_lp.replace('T', ' ')[:16]} | {info} hubs and zones in "
                 "`latest_prices` (newest retrieval) |")
    else:
        L.append(f"| latest prices, every 15 minutes | unknown | {info} |")
    L += ["", "A table that failed is not written that day; nothing partial is. The reasons are in "
          "`warehouse/metadata/run_status.csv`.", ""]

    newest = rs.sort_values("run_id").groupby(["connector", "table"]).tail(1)
    failing_now = newest[newest["status"] == "failed"]
    L += ["## Tables whose last run failed", ""]
    if failing_now.empty:
        L.append("None.")
    else:
        L += ["| Table | Run | Reason |", "|---|---|---|"]
        for r in failing_now.sort_values("table").itertuples():
            L.append(f"| `{r.table}` | {r.run_id} | {r.detail[:160].replace('|', '/')} |")

    gaps = rs[rs["status"] == "gap"].copy()
    # session 34: the market is "<day>", or for a partitioned table "<ba> <day>" or "<ba> <day> <variable>"; a history
    # build records a range ("<ba> <first>..<last> <variable>"), which is listed, not re-checked day by day
    tok = gaps["market"].str.split()
    gaps["day"] = tok.map(lambda t: next((x for x in t if len(x) >= 10 and x[:4].isdigit()), t[-1] if t else ""))
    gaps["part"] = [t[0] if len(t) >= 2 and not t[0][:4].isdigit() else None for t in tok]
    gaps["var"] = [("co2_emissions_" + t[2]) if len(t) >= 3 and "+" not in t[2] else None for t in tok]
    gaps = gaps.sort_values("run_id").drop_duplicates(["table", "part", "day", "var"], keep="last")
    open_rows, closed = [], 0
    for g in gaps.itertuples():
        if ".." in g.day:
            open_rows.append((g.table, f"{g.part} {g.day}", "a range recorded by a history build (run_status.csv)",
                              g.detail[:140].replace("|", "/")))
            continue
        if not is_day(g.day):  # session 149: a gap row for many days at once ("pairs"): listed, not re-checked
            open_rows.append((g.table, g.market, "names no single day (run_status.csv): listed, not re-checked",
                              g.detail[:140].replace("|", "/")))
            continue
        state = day_complete(g.table, g.day, g.part, g.var)
        if state is True:
            closed += 1
            continue
        open_rows.append((g.table, g.day, "not on this machine, not verifiable here" if state is None
                          else "still incomplete in the table", g.detail[:140].replace("|", "/")))
    L += ["", "## Open gaps", "",
          "Days a per-day connector could not write complete, re-checked against the table with the "
          f"connector's own completeness rule. Recorded gap days: {len(gaps)}; filled since: {closed}; "
          f"open: {len(open_rows)}.", ""]
    if open_rows:
        L += ["| Table | Day | State | First recorded reason |", "|---|---|---|---|"]
        for t, d, st, why in sorted(open_rows):
            L.append(f"| `{t}` | {d} | {st} | {why} |")
    else:
        L.append("None.")
    L.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote STATUS.md: {len(cov)} tables, {len(open_rows)} open gaps, {closed} filled, "
          f"latest prices {last_lp or info}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
